### ISSUE TITLE
Quiz questions not covered in material.

### ISSUE THREAD

**Issue by jeffslutzky** [learn-co-curriculum/git-flow#5]
There are several quiz questions that are not covered in the lesson.

**Comment by AnnJohn** [comment]
@SophieDeBenedetto  @jmburges @adamjonas  Does this have anything to do with the pre-work being re-organized?

**Comment by adamjonas** [comment]
Possible. @jmburges and @SophieDeBenedetto would be in a better position to answer but this should be addressed since it's so early in the pre-work track.

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by pletcher** [comment]
Closing. Please feel free to reopen if this is still an issue.
