### ISSUE TITLE
No conflict, when conflict expected

### ISSUE THREAD

**Issue by pedrotp** [learn-co-curriculum/git-flow#7]
In the Merging With Conflicts section, when I tried to merge the add-walrus branch from the add-walrus-and-polar-bear branch, it just merged, no conflicts...

**Comment by AnnJohn** [comment]
Hi @pedrotp sorry for the delay with this. We'll look into it as soon as we can

**Comment by pletcher** [comment]
I'm not able to reproduce this issue (getting the conflict works). I've edited the README to try to make it clearer what needs to happen.
